### ISSUE TITLE
Loading a DLS file has no effect

### ISSUE THREAD

**Issue by M-HT** [EmbeddedSynth/sonivox-fork#11]
Using the example program (`sonivoxrender`) on the testing midi file (`arm-wt-22k/vectors/ants.mid`) produces the same output regardless of whether a DLS file is loaded or not.
Or in other words, these two commands produce the same file:
```
./sonivoxrender ../arm-wt-22k/vectors/ants.mid
./sonivoxrender -d gm.dls ../arm-wt-22k/vectors/ants.mid
```
Tested DLS files were gm.dls from Windows installation and DLS files mentioned in issue #9.

**Comment by pedrolcl** [comment]
Thank you for your contributions.  I've decided that is worth to include your fix in the library.

Please add your valid copyright statement to the README.md document at your convenience.
